### ISSUE TITLE
Streaming from a std::io::Read

### ISSUE THREAD

**Issue by benhansen-io** [rafaelcaricio/qoaudio#1]
Hi, I would like to use QOA in my Rust microcontroller project that is in a restrictive memory environment.  Accordingly I am looking for a streaming API similar to [Hound](https://docs.rs/hound/latest/hound/struct.WavReader.html) where it is performed in a more streaming manner with less buffering/allocation.

From the Hound docs:

> A WavReader is a streaming reader. It reads data from the underlying reader on demand, and it reads no more than strictly necessary. No internal buffering is performed on the underlying reader, but this can easily be added by wrapping the reader in an io::BufReader. The open constructor takes care of this for you.

Is this something this project is interested in for QOA or would it be better if I build a streaming decoder in a separate crate?  Thanks.

**Comment by benhansen-io** [comment]
I am going to give this an attempt and assuming it goes well I'll upload a diff. You can decide if you want to merge it then.

**Comment by rafaelcaricio** [comment]
@benhansen-io I've just released [a new version](https://crates.io/crates/qoaudio/0.6.0) to crates.io with your changes. Thank you so much for the work. Sorry for the delay, I've been on vacation for the last couple of weeks and only now managed to get some time to look into this.

**Comment by benhansen-io** [comment]
Great, thanks and no worries about the delay. Hope you had a great vacation.
